### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by dwxw** [immutable/zkevm-boilerplate#8]
Hello,

I'm not sure where the best place to post this is.  I'm following the [tutorial](https://docs.immutable.com/docs/zkevm/contracts/tutorials/tutorial-forging) associated with this boilerplate project.  A recent change was made in this [PR](https://github.com/immutable/zkevm-boilerplate/pull/7) to add receiver and fee numerator to the`ImmutableERC721PermissionedMintable` contract.  The tutorial is now out of date and I'm not understanding what these values are to carry on myself.  Would appreciate some help as I'd love to learn more about the zkEVM.  Thanks.

**Comment by EdwardJES** [comment]
Hi, 

@dwxw, thank you for raising this concern. You are correct that the docs for the tutorial do not include the latest release. We will aim to have the docs updated and reflect the new changes this week.
